apiVersion: v1
kind: Service
metadata:
  name: ubuntu-receiver
spec:
  ports:
  - port: 2929
    protocol: TCP
    targetPort: 2929
  selector:
    run: ubuntu-receiver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ubuntu-receiver
  name: ubuntu-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ubuntu-receiver
  strategy: {}
  template:
    metadata:
      labels:
        run: ubuntu-receiver
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-nodepool1-23454376-vmss000001
      containers:
      - image: ubuntu
        name: ubuntu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "apt update; apt install netcat -y;while true; do sleep 30; done;" ]