---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: steve.griffith@microsoft.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emqxtlsdemo.stevegriffith.io
  namespace: default
spec:
  dnsNames:
    - emqxtlsdemo.stevegriffith.io
  secretName: emqxtlsdemo.stevegriffith.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
